name: n8n
services:
  n8n-postgres:
    container_name: n8n-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/postgres
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "256MB"
        limits:
          memory: 1024M
    network_mode: bridge

  n8n-redis:
    container_name: n8n-redis
    image: redis:7-alpine
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/redis
        target: /data
    ports:
      - "6380:6379"
    command: redis-server --requirepass n8nredispassword
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "128MB"
        limits:
          memory: 512M
    network_mode: bridge

  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - QUEUE_BULL_REDIS_HOST=n8n-redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=n8nredispassword
      - N8N_ENCRYPTION_KEY=n8n-encryption-key-change-this
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
      - NODE_ENV=production
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_ONBOARDING_FLOW_DISABLED=false
      - N8N_METRICS=false
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=regular
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/data
        target: /home/node/.n8n
      - type: bind
        source: /DATA/AppData/n8n/files
        target: /files
    ports:
      - "5678:5678"
    depends_on:
      - n8n-postgres
      - n8n-redis
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "512MB"
        limits:
          memory: 2048M
    network_mode: bridge

  n8n-webhook:
    container_name: n8n-webhook
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - QUEUE_BULL_REDIS_HOST=n8n-redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=n8nredispassword
      - N8N_ENCRYPTION_KEY=n8n-encryption-key-change-this
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - WEBHOOK_URL=http://localhost:5679
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
      - NODE_ENV=production
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=queue
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/data
        target: /home/node/.n8n
      - type: bind
        source: /DATA/AppData/n8n/files
        target: /files
    ports:
      - "5679:5678"
    depends_on:
      - n8n-postgres
      - n8n-redis
    restart: unless-stopped
    command: n8n webhook
    deploy:
      resources:
        reservations:
          memory: "256MB"
        limits:
          memory: 1024M
    network_mode: bridge

  n8n-worker:
    container_name: n8n-worker
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - QUEUE_BULL_REDIS_HOST=n8n-redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=n8nredispassword
      - N8N_ENCRYPTION_KEY=n8n-encryption-key-change-this
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
      - NODE_ENV=production
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=queue
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/data
        target: /home/node/.n8n
      - type: bind
        source: /DATA/AppData/n8n/files
        target: /files
    depends_on:
      - n8n-postgres
      - n8n-redis
    restart: unless-stopped
    command: n8n worker
    deploy:
      resources:
        reservations:
          memory: "512MB"
        limits:
          memory: 2048M
    network_mode: bridge

  n8n-nginx:
    container_name: n8n-nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
      - target: 443
        published: "8443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/n8n/nginx
        target: /etc/nginx/conf.d
      - type: bind
        source: /DATA/AppData/n8n/ssl
        target: /etc/nginx/ssl
    depends_on:
      - n8n
      - n8n-webhook
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: "64MB"
        limits:
          memory: 256M
    network_mode: bridge

networks:
  default:
    name: n8n-network
    driver: bridge 